name: Perform automatic release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release
        required: true
      next_version:
        type: string
        description: Next version to set for the project
        required: true        
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  main:
    name: Run release
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub App token
      uses: electron/github-app-auth-action@v1.1.1
      id: generate-token
      with:
        creds: ${{ secrets.GH_APP_CREDS }}
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4.1.1
    - name: Set release version
      run: |
        echo 'ThisBuild / version := ${{ inputs.version }}' > version.sbt
        git add version.sbt
    - name: Commit release version
      uses: dsanders11/github-app-commit-action@v1
      with:
        message: 'Setting version to ${{ inputs.version }}'
        token: ${{ steps.generate-token.outputs.token }}
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      with:
        title: Release ${{ inputs.version }}
        tag: v${{ inputs.version }}
    - name: Set next dev version
      run: |
        echo 'ThisBuild / version := ${{ inputs.next_version }}' > version.sbt
        git add version.sbt
    - name: Commit next version
      uses: dsanders11/github-app-commit-action@v1
      with:
        message: 'Setting version to ${{ inputs.next_version }}'
        token: ${{ steps.generate-token.outputs.token }}
        force: true